// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVXyEJ3J6fIjKssjq_VwpyFbmAm4rUio',
    appId: '1:540378750459:web:3905b7e1ff83130466ff5e',
    messagingSenderId: '540378750459',
    projectId: 'calorietracker-74c0d',
    authDomain: 'calorietracker-74c0d.firebaseapp.com',
    storageBucket: 'calorietracker-74c0d.firebasestorage.app',
    measurementId: 'G-MZD4CL68S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RQlLp_7Y00_oofZ6VPpYMCezUQWtLpI',
    appId: '1:540378750459:android:99fc81cbe4f4d13c66ff5e',
    messagingSenderId: '540378750459',
    projectId: 'calorietracker-74c0d',
    storageBucket: 'calorietracker-74c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJn4TYuq6wly8Vw0P_P-dBPQjf2JqMbN0',
    appId: '1:540378750459:ios:3e0a2bcac070356766ff5e', // Match plist
    messagingSenderId: '540378750459',
    projectId: 'calorietracker-74c0d',
    storageBucket: 'calorietracker-74c0d.firebasestorage.app',
    iosBundleId:
        'brotherarts.EdanosAI.FoodNutritionScan.flutter', // Match plist
  );
}
